language: node_js
notifications:
  email:
    on_success: never
    on_failure: never
node_js:
- stable
before_install:
- npm install -g typings gulp-cli npm typedoc
script:
- npm test
- chmod +x ./travis/deploy-gh-pages.sh && ./travis/deploy-gh-pages.sh
before_deploy:
- npm run prestart
deploy:
  provider: heroku
  on:
    branch: production
  app: guido-backend
  skip_cleanup: true
  api_key:
    secure: K9NyA54zkXCINEhHfyacBUsVKZ63OO/QqZJpJqWLDvTJbBE+qn+0SE5zDTdZZ7PDi5z4vrAsWegFd2fldc00vMas5DpOHgpey907Z+Wq9KDF2hTC9GUHD+N5cP3Wp3Z7MYkfpraDzQbel5BbooeU33afP5rMWkbX3l2GR35WJuMXbVqlOnOa1SQcACoeNJroWBEVsqnCtc+zsRmMQwkiKZbP3hokTxDXKOXCkUNZ1jycRbNT/tAQtZhH5rkwoHTJx5elDQMCFWBH6tvAwhFaTYInkFrHpPU5gWuXSRve6MNgkNYLCCSZ73PJsDp7DcuIHTRYXhzGhV6NJPYzRFTqoumQ8bdwqJ3FQfsU8Q8N5eFU0aGw+bcaulC5WrQkvP0TlTAP5WbRTMo7vN6sZVG2pAx5/AyXK4ZH2r2PP91ivPs1Iyimuf3AaZVfOFsq0BwGQczt3A0SMvNrM1tvsrmjEj/NzT1YU39uH5eU0tc054cP8juHnv7H1fYEqYWOyY56/1I10g6SVePBjIb0VvANypILhTqJFMhL/ZIVU6vpryS84ITzz4OsXUob4x0xoIwCUqY0PcRvZcDRrj1JvHs5fGRTeLhUMj0huAUplRKmv6OL82IKhQGKfo/KvlNGl2BFANF6FFNd5o7f1ubNACQ0iGL/OLjzqXUnYfob3Q/9t8M=
